SERVER_URL = "https://ghostsocket.onrender.com"
API_BASE = f"{SERVER_URL}/app"
CHECK_USER_URL = f"{API_BASE}/check-user"
VERIFY_OTP_URL = f"{API_BASE}/verify-otp"
VERIFY_PASSWORD_URL = f"{API_BASE}/verify-password"
RESEND_OTP_URL = f"{API_BASE}/resend-otp"
LOGOUT_APP_URL = f"{API_BASE}/logout-app"
GET_USER_DATA_URL = f"{API_BASE}/get-user-data"
SAVE_PERMISSIONS_URL = f"{API_BASE}/save-permissions"
ENABLE_DISABLE_URL = f"{API_BASE}/enable-disable"
UPDATE_DEVICE_INFO_URL = f"{API_BASE}/update-device-info"

WEB_BASE = "https://ghost-socket.vercel.app"
SIGNUP_BASE = f"{WEB_BASE}/sign-up"
FORGOT_PASSWORD_BASE = f"{WEB_BASE}/sign-in"
MANAGE_ACCOUNT_BASE = f"{WEB_BASE}/sign-in"